### PR TITLE
Sign up

### PR DESCRIPTION
**Pull request by aliceduongg**
Review signup component and make sure inputs are required

### CODE REVIEW

**Review by aliceduongg — COMMENTED** [review]
3 validations for inputs has been added.

**Review by aliceduongg — COMMENTED** [review]
ignore

**Comment by JoePan001** [comment]
valid mail address required
pswd at least 6-characters long
both requirements should be achieved before signing up

**Comment by aliceduongg** [comment]
Firstly, pls change the inputs for Sign up required which include: firstName, lastName, email, password and role. Secondly, when they are signup successfully, "Welcome + firstName" should be displayed, not "Welcome + Email"
Display_check

**Review by aliceduongg — COMMENTED** [review]
Added required fields before proceeding to sign up

**Pull request merged**
